- name: cart component
  hosts: cart
  become: yes
  tasks: 
  - name: need to enable nodejs eighteen and disabel current version
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nidejs:18 -y
  
  - name: Install the nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create user
    ansible.builtin.user:
      name: roboshop

  - name: create application directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp
  
  - name: Extract the application
    ansible.built.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy the cart.service file
    ansible.builtin.copy:
      src: cart.srvice
      dest: /etc/systemd/system
  
  - name: reload the systemd service
    ansible.builtin.systemd_servie:
      daemon_reload: true

  - name: Enable and start the service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes

