- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: need to disable the current version of nodejs and enable nodejs eighteen
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y #used command module due to lack of module for enabel perticular package
  - name:
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: Need to create roboshop user
    ansible.builtin.user:
      name: roboshop
  - name: create directory
    ansible.builtin.file:
        path: /app
        state: directory
  - name: Need to download code which is in URL
    ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
    
  