- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: need to disable the current version of nodejs and enable nodejs 18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y #used command module due to lack of module for enabel perticular package
  - name:
    ansible.builtin.package:
      name: nodejs
      state: present
  