- name: dispatch component
  hosts: dispatch
  become: yes
  tasks:
  - name: install golang
    ansible.builtin.package:
      name: golang
      state: present
  
  - name: create application user
    ansible.builtin.user:
      name: roboshop

  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: Download URL of application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp
  
  - name: Extract the application
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    ansible.builtin.command: go mod init dispatch; go get; go build;

  - name: copy the user service file
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: Reload the systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and restart the service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes
  


 

