- name: rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure yum erlang /ect/yum.repos.d
    ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: configure yum repos for rabbitmq
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: Install rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: enable and restart the service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  
  - name: create user in rabbitmq
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123
    ignore_error: yes

  - name: create user in rabbitmq
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"