- name: user module need to update
  hosts: user
  become: yes
  tasks:
  - name: current version of nodejs need to disable and enable eighteen nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y;

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the user application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: Install dependencies
    ansible.builtin.command: npm install
    args: 
      chdir: /app
  
  - name: unarchieve the application file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: copy the user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: Reload the systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and restart the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  
  - name: check the user count in user
    ansible.builtin.command: mongo --host mongodb.devopsv.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.users.count()'
    register: user_count # output got from above command need to register in user_count variable

  - name: print the user count
    ansible.builtin.debug:
      msg: "user_count: {{user_count}}"

  - name: load user data when count not equal to zero
    ansible.builtin.command: mongo --host mongodb.devopsv.online < /app/schema/user.js
    when: user_count.stdout == 0  
    
  - name: start and enable service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  

  
  


  
  

      
     
